version: '3.8'

services:
  postgres_db:
    image: postgres:14-alpine
    container_name: myreadify_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myreadify_user
      - POSTGRES_PASSWORD=myreadify_password
      - POSTGRES_DB=myreadify_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data