version: '3.8'

services:
  postgres_db:
    image: postgres:14-alpine
    container_name: myreadify_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myreadify_user
      - POSTGRES_PASSWORD=myreadify_password
      - POSTGRES_DB=myreadify_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - myreadify_network

  backend:
    build: .
    container_name: myreadify_backend
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - postgres_db
    env_file:
      - .env.development
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    networks:
      - myreadify_network

networks:
  myreadify_network:
    driver: bridge
