version: '3.8'

services:
  backend:
    build: .
    container_name: myreadify_backend
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: myreadify_db
      DB_USER: postgres
      DB_PASSWORD: myreadify_password

  db:
    image: postgres:14-alpine
    container_name: myreadify_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myreadify_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myreadify_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
